# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, hspec, HUnit, QuickCheck, testFramework
, testFrameworkHunit, testFrameworkQuickcheck2
}:

cabal.mkDerivation (self: {
  pname = "lucrum-core";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  testDepends = [
    hspec HUnit QuickCheck testFramework testFrameworkHunit
    testFrameworkQuickcheck2
  ];
  meta = {
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
